firstname = input('Enter First Name: ')
middlename = input('Enter Middle Name: ')
lastname = input('Enter Last Name: ')
birthdate = input('Enter Date Of Birth (XX-XX-XXXX): ')
grade = input('Enter Your Grade: ')
school = input('Enter Your School: ')
schoolpurpose = input('Enter Description Of School: ')
currentyear = input('Enter Your School Year For This Grade (XXXX-XXXX): ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('      ' + currentyear)
print('   ')
print('   ')
print('   ')
print('   ')
print('      ' + firstname + ' ' + middlename)
print('      ' + lastname)
print('      Date Of Birth: ' + birthdate)
print('        ' + grade)
print(school)
print(schoolpurpose)

print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')
print('   ')